version: '3.7'
services:
  mongodb:
    image: mongo
    volumes:
      - ./mongodb/data/db
    ports:
      - 127.0.0.1:27017:27017

  main-service:
    build:
      context: .
      dockerfile: DockerfileMain
    image: main-service
    volumes:
      - .:/main
    ports:
      - "8080:8080"

  db-service:
    build:
      context: .
      dockerfile: DockerfileDb
    image: db-service
    volumes:
      - .:/main
    ports:
      - "8070:8070"