version: '3.7'
services:
  main-service:
    build:
      context: .
      dockerfile: DockerfileMain
    image: main-service
    volumes:
      - .:/main
    ports:
      - "8080:8080"

  db-service:
    build:
      context: .
      dockerfile: DockerfileDb
    image: db-service
    volumes:
      - .:/main
    ports:
      - "8070:8070"